### PR TITLE
Fix `StartMessageIdInclusive` not work when reader reads from latest msg id

### LINKED ISSUE #385: [Bug] Inclusive start message Id not work when reader reads from latest msg id
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

9ffd2ef45f87e52745d3baad454aae081f035507

### Minimal reproduce step

```
    Client client(serviceUrl);

    const std::string topic = "test-seek-latest-message-id-" + std::to_string(time(nullptr));

    Producer producer;
    ASSERT_EQ(ResultOk, client.createProducer(topic, producer));

    MessageId id;
    ASSERT_EQ(ResultOk, producer.send(MessageBuilder().setContent("msg").build(), id));

    Reader readerExclusive;
    ASSERT_EQ(ResultOk,
              client.createReader(topic, MessageId::latest(), ReaderConfiguration(), readerExclusive));

    Reader readerInclusive;
    ASSERT_EQ(ResultOk,
              client.createReader(topic, MessageId::latest(),
                                  ReaderConfiguration().setStartMessageIdInclusive(true), readerInclusive));

    Message msg;
    bool hasMsgAvaliable = false;
    readerInclusive.hasMessageAvailable(hasMsgAvaliable);
    ASSERT_TRUE(hasMsgAvaliable);
    ASSERT_EQ(ResultOk, readerInclusive.readNext(msg, 3000));
    ASSERT_EQ(ResultTimeout, readerExclusive.readNext(msg, 3000));

    readerExclusive.close();
    readerInclusive.close();
    producer.close();
```

### What did you expect to see?

The test should be passed.
The readerInclusive should be able to read the next message.

### What did you see instead?

The readerInclusive can't read the next message.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #385

### Motivation

The reader with `StartMessageIdInclusive` enabled should be able to reads messages from the latest message ID.

### Modifications

- If `StartMessageIdInclusive` is enabled, the reader will seek and read the latest message in the topic.

### Verifying this change

This change added tests.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
It's a bug fix

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: lib/ConsumerImpl.cc [hunk 1]
```diff
@@ -1508,18 +1508,33 @@ void ConsumerImpl::hasMessageAvailableAsync(HasMessageAvailableCallback callback
 
     if (messageId == MessageId::latest()) {
         lock.unlock();
-        getLastMessageIdAsync([callback](Result result, const GetLastMessageIdResponse& response) {
+        getLastMessageIdAsync([this, callback](Result result, const GetLastMessageIdResponse& response) {
```
Comment (BewareMyPower) [inline lib/ConsumerImpl.cc:1511]: You should capture the `shared_ptr` or `weak_ptr` in case the `ConsumerImpl` instance (that `this` points to) has been destroyed when the callback of `getLastMessageIdAsync` is called.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Comment by Samreay** [comment]
Is there any chance we can get a client with this bugfix released?

**Comment by BewareMyPower** [comment]
You might need to wait for 3.5.0 release maybe at the end of this month.

**Comment by Samreay** [comment]
Is main broken at the moment with an incomplete feature or similar? Not trying to be pushy here, just unsure what process is in the way of releasing bugfixes once they're completed instead of waiting on something unspecified

**Comment by BewareMyPower** [comment]
No. But there is an important fix I'm working on: https://github.com/apache/pulsar-client-cpp/pull/396

And yes, it's okay to drive a 3.5.0 release recently once it's done. I just realized there are about 2 months since the last 3.4.2 release.

**Comment by BewareMyPower** [comment]
Generally, the vote process takes about a week to complete. Specifically, Chinese New Year is coming so I might not have enough time to drive this release next week.

**Comment by Samreay** [comment]
Ah, I didn't realise you had such a length voting system. Sounds like... fun? Good luck with the fixes then, and enjoy Chinese New Year :)
