### PR TITLE
Fix TableView's existing key-value will never be updated

### LINKED ISSUE #486: [Bug] TableView's existing value will never update
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

TableView uses `SynchronizedHashMap#emplace` to update a key-value:

https://github.com/apache/pulsar-client-cpp/blob/0e1ed3b2af24f5373036b839e4131257e8e75bf2/lib/TableViewImpl.cc#L107

https://github.com/apache/pulsar-client-cpp/blob/0e1ed3b2af24f5373036b839e4131257e8e75bf2/lib/SynchronizedHashMap.h#L58

However, the underlying `emplace` method does not update an existing key-value.

### Minimal reproduce step

TBD

### What did you expect to see?

TBD

### What did you see instead?

TBD

### Anything else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #486

### Motivation

The `emplace` method of `SynchronizedHashMap` adopts the same semantics as https://en.cppreference.com/w/cpp/container/map/emplace, which inserts the key-value only when the key does not exist. `TableViewImpl` leverages this method to update the key-values, so it will never succeed. In addition, this method is not thread safe because if the key exists, an iterator will be returned to the caller, then the caller could use the iterator to modify the value without any synchronization.

### Modifications

Add two new methods `putIfAbsent` and `put` and remove the `emplace` method.
- `putIfAbsent`: inserts the key-value only when the key does not exist and return the optional existing value
- `put`: inserts the key-value no matter if the key exists.

Then, replace the `emplace` call with `put` in `TableViewImpl`.

### Verifying this change

`testSimpleTableView` is improved to verify the update case.

### CODE REVIEW

File: lib/ClientImpl.cc [hunk 1]
```diff
@@ -222,12 +222,12 @@ void ClientImpl::handleCreateProducer(const Result result, const LookupDataResul
 void ClientImpl::handleProducerCreated(Result result, ProducerImplBaseWeakPtr producerBaseWeakPtr,
                                        CreateProducerCallback callback, ProducerImplBasePtr producer) {
     if (result == ResultOk) {
-        auto pair = producers_.emplace(producer.get(), producer);
-        if (!pair.second) {
-            auto existingProducer = pair.first->second.lock();
+        auto address = producer.get();
+        auto existingProducer = producers_.create(address, producer);
```
Comment (merlimat) [inline lib/ClientImpl.cc:226]: `create()` is a bit confusing here as a name. I was wondering why do we need to "create a new consumer here"... 

Could we rename the method as `putIfAbsent()`?

**Review by merlimat — APPROVED** [review]

File: lib/ClientImpl.cc (hunk 1 above)
Comment (BewareMyPower) [reply lib/ClientImpl.cc:226]: Yes, it makes sense.

Comment (BewareMyPower) [reply lib/ClientImpl.cc]: I renamed these methods as `put` and `putIfAbsent` now.
