### PR TITLE
Fix Wireshark build

### LINKED ISSUE #179: [Bug] wireshark build points to wrong pulsar-common directory
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

3.1.1. Reproduced on M1 macbook pro but it should affect all OS are affected since it's a bad directory link.

### Minimal reproduce step

1. On a M1 macbook, run steps on https://github.com/apache/pulsar-client-cpp to install dependencies.
2. Run `cmake` command to prepare wireshark build:
```cmake -DBUILD_WIRESHARK=ON -DGTEST_INCLUDE_PATH=/usr/local/Cellar/googletest/1.13.0/include/gtest -DGMOCK_INCLUDE_PATH=/usr/local/Cellar/googletest/1.13.0/include/gmock .```
3. make pulsar-dissector points to a bad directory for pulsar-common.
```make pulsar-dissector
make[3]: *** No rule to make target `/Users/lin/git/pulsar-common/src/main/proto/PulsarApi.proto', needed by `generated/lib/PulsarApi.pb.cc'.  Stop.
make[2]: *** [wireshark/CMakeFiles/pulsar-dissector.dir/all] Error 2
make[1]: *** [wireshark/CMakeFiles/pulsar-dissector.dir/rule] Error 2
make: *** [pulsar-dissector] Error 2```

### What did you expect to see?

`make pulsar-dissector` should be successful.

### What did you see instead?

Error message that points to a bad directory for `pulsar-common`.

### Anything else?

This should be caused by the migration from the core pulsar directory. The script need to be updated to point to the right `pulsar-common` source code for `PulsarApi.proto`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### LINKED ISSUE #180: [Bug] wireshark: 5 (new?) Pulsar commands not supported.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

3.1.1

### Minimal reproduce step

```make pulsar-dissector
[ 33%] Building CXX object wireshark/CMakeFiles/pulsar-dissector.dir/pulsarDissector.cc.o
/Users/lin/git/pulsar-client-cpp/wireshark/pulsarDissector.cc:532:13: error: 5 enumeration values not handled in switch: 'BaseCommand_Type_WATCH_TOPIC_LIST', 'BaseCommand_Type_WATCH_TOPIC_LIST_SUCCESS', 'BaseCommand_Type_WATCH_TOPIC_UPDATE'... [-Werror,-Wswitch]
    switch (command.type()) {
            ^~~~~~~~~~~~~~```

### What did you expect to see?

Compilation should succeed. Even if the plugin doesn't support these five commands, maybe it should be skipped or displayed with generic information, instead of fail to build.

### What did you see instead?

Success build with the new Pulsar commands supported.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### LINKED ISSUE #181: [Bug] wireshark (M1 macbook): pulsar-client-cpp/wireshark/pulsarDissector.cc:19:10: fatal error: 'config.h' file not found
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

3.1.1. Macbook pro M1 version.

Already installed glib

### Minimal reproduce step

glib include dirs are: /usr/local/Cellar/glib/2.74.5/include/glib-2.0;/usr/local/Cellar/glib/2.74.5/lib/glib-2.0/include;/usr/local/opt/gettext/include;/usr/local/Cellar/pcre2/10.42/include

```
 cmake -DPULSAR_DIR=/Users/lin/git/pulsar -DBUILD_WIRESHARK=ON -DGTEST_INCLUDE_PATH=/usr/local/Cellar/googletest/1.13.0/include/gtest -DGMOCK_INCLUDE_PATH=/usr/local/Cellar/googletest/1.13.0/include/gmock .
-- Pulsar Client version: 3.2.0-pre
-- Pulsar Client version macro: 3002000
-- LINK_STATIC:  ON
-- ARCHITECTURE: x86_64
-- BUILD_DYNAMIC_LIB:  ON
-- BUILD_STATIC_LIB:  ON
 w/pulsarDissector.cc+                                                                                                                                                                               ◀◀ buffers
-- BUILD_TESTS:  OFF
-- BUILD_WIRESHARK:  ON
-- BUILD_PERF_TOOLS:  OFF
-- USE_LOG4CXX:  OFF
-- CMAKE_BUILD_TYPE:  RelWithDebInfo
-- Threads library:
Boost_INCLUDE_DIRS: /usr/local/include
OPENSSL_INCLUDE_DIR: /usr/local/opt/openssl/include
OPENSSL_LIBRARIES: /usr/local/opt/openssl/lib/libssl.dylib/usr/local/opt/openssl/lib/libcrypto.dylib
Protobuf_INCLUDE_DIRS: /usr/local/include
Protobuf_LIBRARIES: /usr/local/lib/libprotobuf.dylib
CMake Warning (dev) at /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (CURL) does
  not match the name of the calling package (curl).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/Findcurl.cmake:182 (find_package_handle_standard_args)
  CMakeLists.txt:154 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CURL_INCLUDE_DIRS: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include
CURL_LIBRARIES: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/lib/libcurl.tbd
CMake Warning (dev) at /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (ZLIB) does
  not match the name of the calling package (zlib).  This can lead to
  problems in calling code that expects `find_package` result variables
 w/pulsarDissector.cc+                                                                                                                                                                               ◀◀ buffers
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/Findzlib.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:165 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

ZLIB_INCLUDE_DIRS: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include
ZLIB_LIBRARIES: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/lib/libz.tbd
-- ZStd: /usr/local/lib/libzstd.dylib
-- LIB_SNAPPY: /usr/local/lib/libsnappy.a
-- HAS_ZSTD: 1
-- HAS_SNAPPY: 1
-- Use WIRESHARK_BUILD_TYPE: RelWithDebInfo
-- Use WIRESHARK_LIB: WIRESHARK_LIB-NOTFOUND
-- Use WIRESHARK_UTIL_LIB: WIRESHARK_UTIL_LIB-NOTFOUND
-- Use WIRESHARK_INCLUDE_PATH: WIRESHARK_INCLUDE_PATH-NOTFOUND
-- Use GLIB_INCLUDE_DIRS: /usr/local/Cellar/glib/2.74.5/include/glib-2.0;/usr/local/Cellar/glib/2.74.5/lib/glib-2.0/include;/usr/local/opt/gettext/include;/usr/local/Cellar/pcre2/10.42/include
-- Use PULSAR_DIR: /Users/lin/git/pulsar
clang-tidy not found
clang-format not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lin/git/pulsar-client-cpp
Lins-MacBook-Pro:pulsar-client-cpp lin$ make pulsar-dissector
[ 33%] Generating ../generated/lib/PulsarApi.pb.cc, ../generated/lib/PulsarApi.pb.h
[ 66%] Building CXX object wireshark/CMakeFiles/pulsar-dissector.dir/pulsarDissector.cc.o
/Users/lin/git/pulsar-client-cpp/wireshark/pulsarDissector.cc:19:10: fatal error: 'config.h' file not found
#include <config.h>
         ^~~~~~~~~~
1 error generated.
make[3]: *** [wireshark/CMakeFiles/pulsar-dissector.dir/pulsarDissector.cc.o] Error 1
make[2]: *** [wireshark/CMakeFiles/pulsar-dissector.dir/all] Error 2
make[1]: *** [wireshark/CMakeFiles/pulsar-dissector.dir/rule] Error 2
```

### What did you expect to see?

Build should succeed. 

Interestingly, if I commend out `#include <config.h>`, compilation would continue seemingly without issue. And in the new glib include directories, there's `glibconfig.h` instead of `config.h`.
Maybe `#include <glib.h>` is all we need?

### What did you see instead?

Compile failure as above.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Demogorgon314**
* Fixes #181
* Fixes #179
* Fixes #180

### Motivation

The Pulsar Wireshark plugin has not been maintained for a long time, 
the Pulsar protobuf command and Wireshark header file have been updated.

### Modifications
1. Fix protobuf file path
2. Fix the Wireshark header
3. Fix README base path

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

File: wireshark/pulsarDissector.cc [hunk 1]
```diff
@@ -16,15 +16,13 @@
...
-#include <config.h>
 #include <epan/column-utils.h>
 #include <epan/dissectors/packet-tcp.h>
-#include <epan/expert.h>
 #include <epan/packet.h>
-#include <epan/prefs.h>
 #include <epan/proto.h>
 #include <epan/value_string.h>
 #include <glib.h>
+#include <ws_version.h>
```
Comment (BewareMyPower) [inline wireshark/pulsarDissector.cc:25]: This header does not work for the `wireshark-dev` (3.2.3) on Ubuntu. It seems to be caused by the breaking change of the wireshark.

Anyway, currently we can focus on the wireshark 4.x support. So this comment is not a blocker.

Comment (Demogorgon314) [reply wireshark/pulsarDissector.cc:25]: Yes, we can fix it for old version support later if necessary.
