### PR TITLE
[fix] Fix log for connection disconnected expectedly

### LINKED ISSUE #140: [Bug] The log shows `ConnectError` when closing the client
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

main branch

### Minimal reproduce step

When running produce and consume, and the client calls close, it
shows `ConnectError` in the close method
 ```
2022-12-09 03:33:45.288 INFO  [139648501270080] ConsumerImpl:1083 |
[persistent://public/default/basic_e2e_example, sub, 0] Closed
consumer 0
2022-12-09 03:33:45.289 INFO  [139648476091968] ClientConnection:1584
| [[127.0.0.1:43644](http://127.0.0.1:43644/) -> [127.0.0.1:6650](http://127.0.0.1:6650/)] Connection closed with
ConnectError
2022-12-09 03:33:45.289 INFO  [139648476091968] ClientConnection:267 |
[[127.0.0.1:43644](http://127.0.0.1:43644/) -> [127.0.0.1:6650](http://127.0.0.1:6650/)] Destroyed connection
```

### What did you expect to see?

Shows `Disconnected`

### What did you see instead?

Shows `ConnectError`

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #140

### Motivation

When running produce and consume, and the client calls close, it
shows `ConnectError` in the close method

```
[[127.0.0.1:43644](http://127.0.0.1:43644/) -> [127.0.0.1:6650](http://127.0.0.1:6650/)] Connection closed with
ConnectError
```

### Modifications

* Show `Connection disconnected` just like the java client did instead of `ConnectError` when the client disconnect successfully.
* Add error log for unexpected closed connection.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: lib/ClientConnection.cc [hunk 1]
```diff
@@ -1596,7 +1596,11 @@ void ClientConnection::close(Result result) {
     }
 
     lock.unlock();
-    LOG_INFO(cnxString_ << "Connection closed with " << result);
+    if (result != ResultDisconnected) {
+        LOG_ERROR(cnxString_ << "Connection closed with " << result);
```
Comment (shibd) [inline lib/ClientConnection.cc:1600]: When the result is `ResultRetryable`, is there no need to print the error log here?

BTW: I think just print the info level log here because calling close is the expected behavior of the code.

Comment (RobertIndie) [reply lib/ClientConnection.cc:1600]: Thanks. I changed it to print info log when the result is ResultRetryable.
> calling close is the expected behavior of the code.
Many calling of the close is unexpected behavior. such as：

https://github.com/apache/pulsar-client-cpp/blob/5d5ed2acc2e89aed90b593343369f360644440e7/lib/ClientConnection.cc#L485-L491

https://github.com/apache/pulsar-client-cpp/blob/5d5ed2acc2e89aed90b593343369f360644440e7/lib/ClientConnection.cc#L213-L219

https://github.com/apache/pulsar-client-cpp/blob/5d5ed2acc2e89aed90b593343369f360644440e7/lib/ClientConnection.cc#L223-L229

etc...

Comment (shibd) [reply lib/ClientConnection.cc:1600]: As you provided the example, The call `close` may have been an unexpected behavior, so we printed the error log before the call. But inside the `close` method, the execution close method behaves as expected and is closed correctly.

Comment (RobertIndie) [reply lib/ClientConnection.cc:1600]: It will pass the default result value `ResultConnectError` to the `close()` to indicate that the connection is closed unexpectedly. 
In addition, the info log with the `ConnectError` message seems confusing.

Comment (shibd) [reply lib/ClientConnection.cc:1600]: Okay, I agree.

**Review by shibd — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]
