### PR TITLE
[fix] Use unique topic name in ConsumerInterceptorsTest

### LINKED ISSUE #229: Flaky test: ConsumerInterceptorsTest.TestNegativeAcksSend
[example failure](https://github.com/apache/pulsar-client-cpp/actions/runs/4501817436/jobs/7922762277?pr=228)

```
FAILED TESTS (5/488):
     264 ms: ./pulsar-tests Pulsar/ConsumerInterceptorsTest.TestNegativeAcksSend/0 (try #1)
     257 ms: ./pulsar-tests Pulsar/ConsumerInterceptorsTest.TestNegativeAcksSend/2 (try #1)
     220 ms: ./pulsar-tests Pulsar/ConsumerInterceptorsTest.TestNegativeAcksSend/2 (try #2)
     158 ms: ./pulsar-tests Pulsar/ConsumerInterceptorsTest.TestNegativeAcksSend/2 (try #3)
     175 ms: ./pulsar-tests Pulsar/ConsumerInterceptorsTest.TestNegativeAcksSend/2 (try #4)
```

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #229

### Motivation

Using `time(nulltpr)` is not enough for generating the unique topic name. Especially when running a test for less than a second.

### Modifications

* Use `unique_str` to generate the topic name in ConsumerInterceptorsTest

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: tests/InterceptorsTest.cc [hunk 1]
```diff
@@ -272,8 +273,11 @@ class ConsumerTestInterceptor : public ConsumerInterceptor {
 class ConsumerInterceptorsTest : public ::testing::TestWithParam<std::tuple<TopicType, int>> {
    public:
     void SetUp() override {
-        topic_ = "persistent://public/default/InterceptorsTest-ConsumerInterceptors-" +
-                 std::to_string(time(nullptr));
```
Comment (shibd) [inline tests/InterceptorsTest.cc:276]: You can just splice `GetParam()`.

Comment (RobertIndie) [reply tests/InterceptorsTest.cc:276]: Using `GetParam()` couldn't solve the issue. Multiple tests share the same params. If we want to splice `GetParam()`, we also need to add the `current test method` name to the test topic name. But this PR seems simpler.

**Comment by BewareMyPower** [comment]
I think the root cause is that the time unit of `time()` is second.

IMO, you can reuse the `unique_str` function defined in `BasicEndToEndTest.cc` because the time unit is nanosecond. `AcknowledgeTest`, `MemoryLimitTest` and `TypedMessageTest` all reuse this function.

**Comment by RobertIndie** [comment]
> I think the root cause is that the time unit of `time()` is second.

That's also correct.

 
> IMO, you can reuse the `unique_str` function defined in `BasicEndToEndTest.cc` because the time unit is nanosecond. `AcknowledgeTest`, `MemoryLimitTest` and `TypedMessageTest` all reuse this function.

Thanks for that information. `unique_str()` is a more elegant way to generate a unique topic.

**Review by BewareMyPower — APPROVED** [review]
