### PR TITLE
[fix] Handle exceptions when creating timers when fd limit is reached

### LINKED ISSUE #202: [Bug] Exception could be thrown when creating producers or consumers
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

- OS: Ubuntu 20.04
- Pulsar: 2.11.0
- C++ Client: main branch (05807bdaf3a4341b22efd7c71f7b00c47cc31413)

### Minimal reproduce step

```c++
#include <errno.h>
#include <pulsar/Client.h>
#include <string.h>
#include <sys/resource.h>
using namespace pulsar;

int main() {
    struct rlimit oldLimit;
    if (getrlimit(RLIMIT_NOFILE, &oldLimit) < 0) {
        std::cerr << "Failed to get rlimit: " << strerror(errno) << std::endl;
        return 1;
    }
    std::cout << "original limit: " << oldLimit.rlim_cur << " " << oldLimit.rlim_max << std::endl;

    struct rlimit rlimit;
    rlimit.rlim_cur = 1;
    rlimit.rlim_max = oldLimit.rlim_max;

    if (setrlimit(RLIMIT_NOFILE, &rlimit) < 0) {
        std::cerr << "Failed to set rlimit: " << strerror(errno) << std::endl;
        return 1;
    }

    Client client("pulsar://localhost:6650");
    Producer producer;
    auto result = client.createProducer("my-topic", producer);
    if (result != ResultOk) {
        std::cerr << "Failed to create producer " << result << ", try to reset the RLIMIT_NOFILE"
                  << std::endl;
    }

    if (setrlimit(RLIMIT_NOFILE, &oldLimit) < 0) {
        std::cerr << "Failed to set rlimit: " << strerror(errno) << std::endl;
        return 1;
    }

    result = client.createProducer("my-topic", producer);
    if (result != ResultOk) {
        std::cerr << "Failed to create producer " << result << std::endl;
        return 2;
    }

    client.close();
}
```

### What did you expect to see?

1. The 1st `createProducer` call returns `ResultConnectError` because of the file descriptor limit.
2. The 2nd `createProducer` call returns `ResultOk`.

### What did you see instead?

```
2023-02-20 10:02:41.489 ERROR [140184068893696] ClientConnection:186 | Failed to initialize connection: eventfd_select_interrupter: Too many open files [system:24]
2023-02-20 10:02:41.489 INFO  [140184068893696] ClientConnection:1650 | [<none> -> pulsar://localhost:6650] Connection disconnected
2023-02-20 10:02:41.489 INFO  [140184068893696] ConnectionPool:97 | Created connection for pulsar://localhost:6650
2023-02-20 10:02:41.489 INFO  [140184068893696] ClientConnection:270 | [<none> -> pulsar://localhost:6650] Destroyed connection
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  eventfd_select_interrupter: Too many open files [system:24]
Aborted
```

### Anything else?

If we increased the limit from 1 to 5, i.e. changed 

```c++
    rlimit.rlim_cur = 1;
```

to

```c++
    rlimit.rlim_cur = 5;
```

then it would work as expected:

```
original limit: 1024 1048576
2023-02-20 10:04:54.863 INFO  [140200259120128] ClientConnection:191 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2023-02-20 10:04:54.863 INFO  [140200259120128] ConnectionPool:97 | Created connection for pulsar://localhost:6650
2023-02-20 10:04:54.864 ERROR [140200259073792] ClientConnection:564 | [<none> -> pulsar://localhost:6650] Resolve error: asio.netdb:1 : Host not found (authoritative)
2023-02-20 10:04:54.865 ERROR [140200259073792] ClientConnection:1648 | [<none> -> pulsar://localhost:6650] Connection closed with ConnectError
2023-02-20 10:04:54.865 ERROR [140200259073792] ClientImpl:201 | Error Checking/Getting Partition Metadata while creating producer on persistent://public/default/my-topic -- ConnectError
Failed to create producer ConnectError, try to reset the RLIMIT_NOFILE
2023-02-20 10:04:54.865 INFO  [140200259073792] ClientConnection:270 | [<none> -> pulsar://localhost:6650] Destroyed connection
2023-02-20 10:04:54.865 INFO  [140200259120128] ConnectionPool:86 | Deleting stale connection from pool for pulsar://localhost:6650 use_count: -1 @ 0
2023-02-20 10:04:54.865 INFO  [140200259120128] ClientConnection:191 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2023-02-20 10:04:54.865 INFO  [140200259120128] ConnectionPool:97 | Created connection for pulsar://localhost:6650
2023-02-20 10:04:54.867 WARN  [140200259073792] ClientConnection:457 | [<none> -> pulsar://localhost:6650] Failed to establish connection: Connection refused
2023-02-20 10:04:54.868 INFO  [140200259073792] ClientConnection:389 | [127.0.0.1:34564 -> 127.0.0.1:6650] Connected to broker
2023-02-20 10:04:54.873 INFO  [140200259073792] HandlerBase:72 | [persistent://public/default/my-topic-partition-0, ] Getting connection from pool
2023-02-20 10:04:54.876 INFO  [140200259073792] ProducerImpl:205 | [persistent://public/default/my-topic-partition-0, ] Created producer on broker [127.0.0.1:34564 -> 127.0.0.1:6650]
2023-02-20 10:04:54.876 INFO  [140200259120128] ClientImpl:529 | Closing Pulsar client with 1 producers and 0 consumers
2023-02-20 10:04:54.877 INFO  [140200259120128] ProducerImpl:745 | [persistent://public/default/my-topic-partition-0, standalone-100-13] Closing producer for topic persistent://public/default/my-topic-partition-0
2023-02-20 10:04:54.878 INFO  [140200259073792] ProducerImpl:709 | [persistent://public/default/my-topic-partition-0, standalone-100-13] Closed producer 0
2023-02-20 10:04:54.879 ERROR [140200259073792] ClientConnection:835 | [127.0.0.1:34564 -> 127.0.0.1:6650] Connection already disconnected
2023-02-20 10:04:54.879 INFO  [140200233862912] ClientConnection:1650 | [127.0.0.1:34564 -> 127.0.0.1:6650] Connection disconnected
2023-02-20 10:04:55.379 INFO  [140200259120128] ProducerImpl:699 | Producer - [persistent://public/default/my-topic-partition-0, standalone-100-13] , [batchMessageContainer = { BatchMessageContainer [size = 0] [bytes = 0] [maxSize = 1000] [maxBytes = 131072] [topicName = persistent://public/default/my-topic-partition-0] [numberOfBatchesSent_ = 1] [averageBatchSize_ = 0] }]
2023-02-20 10:04:55.379 INFO  [140200259120128] ClientConnection:270 | [127.0.0.1:34564 -> 127.0.0.1:6650] Destroyed connection
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #202

### Motivation

When a `deadline_timer` is constructed, `boost::system::system_error` would be thrown if the fd limit is reached. In this case, the following APIs would fail with exception instead of returning a `Result`:
- `createProducer`
- `subscribe`
- `createReader`

P.S. This behavior is not documented in Boost's documents.

Generally, we should not allow exceptions being thrown from those APIs because we return a `Result` to indicate the error. In addition, these exceptions cannot be caught by the wrapper of other languages.

There is a similar issue: https://github.com/apache/pulsar/issues/14582. However, https://github.com/apache/pulsar/pull/14587 only fixes the case when creating a `socket`. The exception from the constructor of `deadline_timer` is not processed.

### Modifications

Handle the exceptions when creating a socket or timer from `ExecutorService` to restart this executor, then propagate a `std::runtime_error`. Don't allow creating a timer directly from `io_service` so that exceptions can be handled well.

In addition, catch the `runtime_error` when:
- Creating a producer (`ProducerImpl` and `PartitionedProducerImpl`)
- Creating a consumer (`ConsumerImpl` and `MultiTopicsConsumerImpl`)
- Creating a reader (`ReaderImpl`)

because the constructors of them all create at least one timer.

### Verifications

Add `tests/unix/ConnectionFailTest.cc` for Unix systems because `setrlimit` is a POSIX API. It covers the cases when the fd limit is not enough to create a producer, a consumer and a reader.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by shibd — APPROVED** [review]

File: lib/PartitionedProducerImpl.cc [hunk 1]
```diff
@@ -439,26 +439,40 @@ void PartitionedProducerImpl::handleGetPartitions(Result result,
...
                 if (!lazy) {
                     producer->start();
                 }
-                producers_.push_back(producer);
             }
             producersLock.unlock();
             // `runPartitionUpdateTask()` will be called in `handleSinglePartitionProducerCreated()`
             interceptors_->onPartitionsChange(getTopic(), newNumPartitions);
-            return;
+            runPartitionUpdateTask();
```
Comment (RobertIndie) [inline lib/PartitionedProducerImpl.cc:470]: As for the comment at line 468, seems we don't need to call `runPartitionUpdateTask` here

Comment (BewareMyPower) [reply lib/PartitionedProducerImpl.cc]: Yes, it's right, I forgot it. Addressed by moving the comment before the `return`.

**Review by RobertIndie — APPROVED** [review]
