### PR TITLE
[fix] Fix consumer doesn't acknowledge all chunk message Ids

### LINKED ISSUE #320: [Bug] Msgbacklog is not cleared when individual acknowledge chunked messages
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

Reproducible code:
```cpp
TEST_P(MessageChunkingTest, testEndToEnd) {
    const std::string topic =
        "MessageChunkingTest-EndToEnd-" + toString(GetParam()) + std::to_string(time(nullptr));
    Consumer consumer;
    createConsumer(topic, consumer);
    Producer producer;
    createProducer(topic, producer);

    constexpr int numMessages = 10;

    std::vector<MessageId> sendMessageIds;
    for (int i = 0; i < numMessages; i++) {
        MessageId messageId;
        ASSERT_EQ(ResultOk, producer.send(MessageBuilder().setContent(largeMessage).build(), messageId));
        auto chunkMsgId =
            std::dynamic_pointer_cast<ChunkMessageIdImpl>(PulsarFriend::getMessageIdImpl(messageId));
        ASSERT_TRUE(chunkMsgId);
        LOG_INFO("Send " << i << " to " << messageId);
        sendMessageIds.emplace_back(messageId);
    }

    Message msg;
    std::vector<MessageId> receivedMessageIds;
    for (int i = 0; i < numMessages; i++) {
        ASSERT_EQ(ResultOk, consumer.receive(msg, 3000));
        LOG_INFO("Receive " << msg.getLength() << " bytes from " << msg.getMessageId());
        ASSERT_EQ(msg.getDataAsString(), largeMessage);
        ASSERT_EQ(msg.getMessageId().batchIndex(), -1);
        ASSERT_EQ(msg.getMessageId().batchSize(), 0);
        auto messageId = msg.getMessageId();
        auto chunkMsgId =
            std::dynamic_pointer_cast<ChunkMessageIdImpl>(PulsarFriend::getMessageIdImpl(messageId));
        ASSERT_TRUE(chunkMsgId);
        receivedMessageIds.emplace_back(messageId);
        consumer.acknowledge(messageId);
    }
    ASSERT_EQ(receivedMessageIds, sendMessageIds);
    ASSERT_EQ(receivedMessageIds.front().ledgerId(), receivedMessageIds.front().ledgerId());
    ASSERT_GT(receivedMessageIds.back().entryId(), numMessages);

    // Verify the cache has been cleared
    auto& chunkedMessageCache = PulsarFriend::getChunkedMessageCache(consumer);
    ASSERT_EQ(chunkedMessageCache.size(), 0);

    BrokerConsumerStats consumerStats;
    waitUntil(
        std::chrono::seconds(10),
        [&] {
            if (consumer.getBrokerConsumerStats(consumerStats) != ResultOk) return false;
            LOG_DEBUG(consumerStats);
            return consumerStats.getMsgBacklog() == 0;
        },
        1000);
    ASSERT_EQ(consumerStats.getMsgBacklog(), 0); // Msg back log doesn't get cleared

    producer.close();
    consumer.close();
}
```

### What did you expect to see?

The message backlog should be cleared. The above test should be passed.

### What did you see instead?

The backlog doesn't get cleared.

### Anything else?

The root cause is the consumer doesn't acknowledge all chunk message Ids

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #320

### Motivation

Currently, the consumer only acknowledges the last chunk message ID. This will lead to some messages not being acknowledged and the message backlog doesn't get cleaned up.

### Modifications

Add the chunk message Id list into the ChunkedMessageIdImpl. When the consumer acknowledges a chunked message , it will acknowledge all message Ids in that list

### Verifying this change

This change is already covered by existing tests.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: lib/ProducerImpl.cc [hunk 1]
```diff
@@ -912,10 +912,9 @@ bool ProducerImpl::ackReceived(uint64_t sequenceId, MessageId& rawMessageId) {
 
     if (op.chunkedMessageId) {
```
Comment (BewareMyPower) [inline lib/ProducerImpl.cc:913]: It seems that `OpSendMsg::chunkedMessageId` field is not necessary. It's added just to indicate if the current `OpSendMsg` is related to a chunk. But `OpSendMsg::numChunks` can also be used for that.

Without saving an empty `ChunkMessageIdImpl`, we can just merge `setChunkedMessageIds` to the current constructor:

```c++
    ChunkMessageIdImpl(std::vector<MessageId>&& chunkedMessageIds)
        : chunkedMessageIds_(std::move(chunkedMessageIds)) {
        auto lastChunkMsgId = chunkedMessageIds_.back();
        this->ledgerId_ = lastChunkMsgId.ledgerId();
        this->entryId_ = lastChunkMsgId.entryId();
        this->partition_ = lastChunkMsgId.partition();
    }
```

After that, in `ConsumerImpl` we can write:

```c++
    ChunkMessageIdImplPtr chunkMsgId =
        std::make_shared<ChunkMessageIdImpl>(chunkedMsgCtx.moveChunkedMessageIds());
```

and in `ProducerImpl`:

```c++
    if (op.numChunks > 1) {
        // Handling the chunk message id.
        op.chunkMessageIdList.push_back(messageId);
        if (op.chunkId == op.numChunks - 1) {
            auto chunkedMessageId = std::make_shared<ChunkMessageIdImpl>(std::move(op.chunkMessageIdList));
            messageId = chunkedMessageId->build();
        }
```

File: lib/ChunkMessageIdImpl.h [hunk 2]
```diff
@@ -30,19 +30,24 @@ class ChunkMessageIdImpl : public MessageIdImpl, public std::enable_shared_from_
...
+        return chunkedMessageIds_.front().impl_;
     }
 
-    std::shared_ptr<const MessageIdImpl> getFirstChunkMessageId() const { return firstChunkMsgId_; }
+    std::vector<MessageId> moveChunkedMessageIds() noexcept { return std::move(chunkedMessageIds_); }
 
     MessageId build() { return MessageId{std::dynamic_pointer_cast<MessageIdImpl>(shared_from_this())}; }
 
    private:
     std::shared_ptr<MessageIdImpl> firstChunkMsgId_;
```
Comment (BewareMyPower) [inline lib/ChunkMessageIdImpl.h:50]: This field becomes useless after having the `chunkedMessageIds_`.

File: lib/AckGroupingTracker.cc [hunk 3]
```diff
@@ -84,29 +94,43 @@ void AckGroupingTracker::doImmediateAck(const std::set<MessageId>& msgIds, Resul
...
 
+    std::set<MessageId> ackMsgIds;
+
+    for (const auto& msgId : msgIds) {
+        if (auto chunkMessageId =
+                std::dynamic_pointer_cast<ChunkMessageIdImpl>(Commands::getMessageIdImpl(msgId))) {
+            auto msgIdList = chunkMessageId->moveChunkedMessageIds();
+            doImmediateAck(std::set<MessageId>(std::make_move_iterator(msgIdList.begin()),
+                                               std::make_move_iterator(msgIdList.end())),
+                           callback);
```
Comment (BewareMyPower) [inline lib/AckGroupingTracker.cc:105]: We should add `ChunkMessageIdImpl::chunkedMessageIds_` into the `ackMsgIds` instead of calling `doImmediateAck`.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: lib/AckGroupingTracker.cc [hunk 4]
```diff
@@ -42,6 +44,14 @@ void AckGroupingTracker::doImmediateAck(const MessageId& msgId, ResultCallback c
         }
         return;
     }
+    if (auto chunkMessageId =
+            std::dynamic_pointer_cast<ChunkMessageIdImpl>(Commands::getMessageIdImpl(msgId))) {
+        auto msgIdList = chunkMessageId->moveChunkedMessageIds();
+        doImmediateAck(std::set<MessageId>(std::make_move_iterator(msgIdList.begin()),
+                                           std::make_move_iterator(msgIdList.end())),
```
Comment (BewareMyPower) [inline lib/AckGroupingTracker.cc:51]: If the `ackType` is cumulative, we should acknowledge the last message id cumulatively instead of acknowledging all message ids individually.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: lib/ConsumerImpl.cc [hunk 5]
```diff
@@ -1165,6 +1164,9 @@ bool ConsumerImpl::isCumulativeAcknowledgementAllowed(ConsumerType consumerType)
 
 std::pair<MessageId, bool> ConsumerImpl::prepareIndividualAck(const MessageId& messageId) {
     auto messageIdImpl = Commands::getMessageIdImpl(messageId);
+    if (std::dynamic_pointer_cast<ChunkMessageIdImpl>(messageIdImpl)) {
+        return std::make_pair(messageId, true);
```
Comment (BewareMyPower) [inline lib/ConsumerImpl.cc:1168]: Why not fall through to the following if branch?

```c++
    auto batchedMessageIdImpl = std::dynamic_pointer_cast<BatchedMessageIdImpl>(messageIdImpl);

    auto batchSize = messageId.batchSize();
    if (!batchedMessageIdImpl || batchedMessageIdImpl->ackIndividual(messageId.batchIndex())) {
        consumerStatsBasePtr_->messageAcknowledged(ResultOk, CommandAck_AckType_Individual,
                                                   (batchSize > 0) ? batchSize : 1);
        unAckedMessageTrackerPtr_->remove(messageId);
        possibleSendToDeadLetterTopicMessages_.remove(messageId);
```

We can check if it's a `ChunkmessageIdImpl` before returning so that we won't call `discardBatch` on a `ChunkmessageIdImpl`.

File: lib/ProducerImpl.cc [hunk 6]
```diff
@@ -912,10 +912,9 @@ bool ProducerImpl::ackReceived(uint64_t sequenceId, MessageId& rawMessageId) {
...
         // Handling the chunk message id.
-        if (op.chunkId == 0) {
-            op.chunkedMessageId->setFirstChunkMessageId(messageId);
-        } else if (op.chunkId == op.numChunks - 1) {
-            op.chunkedMessageId->setLastChunkMessageId(messageId);
+        op.chunkMessageIdList.push_back(messageId);
+        if (op.chunkId == op.numChunks - 1) {
+            op.chunkedMessageId->setChunkedMessageIds(std::move(op.chunkMessageIdList));
             messageId = op.chunkedMessageId->build();
```
Comment (BewareMyPower) [inline lib/ProducerImpl.cc:918]: BTW, this logic seems wrong? We create `OpSendMsgs` for each single chunk. It seems that `op.chunkMessageIdList` still has 1 item.

File: lib/AckGroupingTracker.cc (hunk 4 above)
Comment (shibd) [reply lib/AckGroupingTracker.cc:51]: +1

File: lib/AckGroupingTracker.cc (hunk 3 above)
Comment (shibd) [reply lib/AckGroupingTracker.cc:105]: +1 that will make the code more clear.

**Comment by shibd** [comment]
BTW: This variable seems useless.

https://github.com/apache/pulsar-client-cpp/blob/0ffad7b838c38ead258a52969fab302f22ccb976/lib/ConsumerImpl.h#L298

**Review by shibd — APPROVED** [review]

**Comment by BewareMyPower** [comment]
I will review this PR again after backing from the vacation in 6th Oct.

File: lib/ChunkMessageIdImpl.h [hunk 7]
```diff
@@ -28,21 +28,21 @@ class ChunkMessageIdImpl;
...
+        auto lastChunkMsgId = chunkedMessageIds_.back();
+        this->ledgerId_ = lastChunkMsgId.ledgerId();
+        this->entryId_ = lastChunkMsgId.entryId();
+        this->partition_ = lastChunkMsgId.partition();
     }
 
-    std::shared_ptr<const MessageIdImpl> getFirstChunkMessageId() const { return firstChunkMsgId_; }
+    const std::vector<MessageId>& getChunkedMessageIds() const noexcept { return chunkedMessageIds_; }
+
+    std::vector<MessageId> moveChunkedMessageIds() noexcept { return std::move(chunkedMessageIds_); }
```
Comment (BewareMyPower) [inline lib/ChunkMessageIdImpl.h:41]:
```suggestion
```

This method is never used.

**Review by BewareMyPower — APPROVED** [review]
