### PR TITLE
Fix TableViewTest.testCreateTableView flaky test.

### LINKED ISSUE #212: [Flaky Test] TableViewTest.testCreateTableView
[example failure](https://github.com/apache/pulsar-client-cpp/actions/runs/4413485517/jobs/7734003726)

logs:

```
2023-03-14 08:14:50.946 INFO  [140646644332096] TableViewImpl:150 | Started table view for persistent://public/default/testCreateTableView1678781690Replayed: 0 message in 2 millis
2023-03-14 08:14:50.946 INFO  [140646647455488] ConsumerImpl:1188 | [persistent://public/default/testCreateTableView1678781690, reader-4bfb633495, 1] Closing consumer for topic persistent://public/default/testCreateTableView1678781690
2023-03-14 08:14:50.946 WARN  [140646644332096] TableViewImpl:165 | Reader persistent://public/default/testCreateTableView1678781690 was interrupted: AlreadyClosed
2023-03-14 08:14:50.946 INFO  [140646644332096] ConsumerImpl:1174 | [persistent://public/default/testCreateTableView1678781690, reader-4bfb633495, 1] Closed consumer 1
2023-03-14 08:14:50.947 INFO  [140646647455488] ClientImpl:581 | Closing Pulsar client with 1 producers and 0 consumers
2023-03-14 08:14:50.947 INFO  [140646647455488] ProducerImpl:754 | [persistent://public/default/testCreateTableView1678781690, standalone-0-2013] Closing producer for topic persistent://public/default/testCreateTableView1678781690
2023-03-14 08:14:50.948 INFO  [140646644332096] HandlerBase:72 | [persistent://public/default/testCreateTableView1678781690, reader-7258b5c90f, 2] Getting connection from pool
2023-03-14 08:14:50.950 INFO  [140646644332096] ProducerImpl:718 | [persistent://public/default/testCreateTableView1678781690, standalone-0-2013] Closed producer 0
2023-03-14 08:14:50.953 WARN  [140646644332096] ClientConnection:1590 | [[::1]:47680 -> [::1]:6650] Received error response from server: IncompatibleSchema (Incompatible schema: exists schema type JSON, new schema type AVRO) -- req_id: 6
2023-03-14 08:14:50.953 ERROR [140646644332096] ConsumerImpl:303 | [persistent://public/default/testCreateTableView1678781690, reader-7258b5c90f, 2] Failed to create consumer: IncompatibleSchema
/home/runner/work/pulsar-client-cpp/pulsar-client-cpp/tests/TableViewTest.cc:63: Failure
Value of: result == ResultDisconnected || result == ResultAlreadyClosed
  Actual: false
Expected: true
2023-03-14 08:14:50.957 INFO  [140646593988160] ClientConnection:1200 | [[::1]:47680 -> [::1]:6650] Connection disconnected
2023-03-14 08:14:50.958 INFO  [140646647455488] ProducerImpl:708 | Producer - [persistent://public/default/testCreateTableView1678781690, standalone-0-2013] , [batchMessageContainer = { BatchMessageContainer [size = 0] [bytes = 0] [maxSize = 1000] [maxBytes = 131072] [topicName = persistent://public/default/testCreateTableView1678781690] [numberOfBatchesSent_ = 1] [averageBatchSize_ = 0] }]
2023-03-14 08:14:50.958 INFO  [140646647455488] ClientConnection:262 | [[::1]:47680 -> [::1]:6650] Destroyed connection
[  FAILED  ] TableViewTest.testCreateTableView (65 ms)
```

### PR DESCRIPTION
**Pull request by shibd**
Fixes #212

### Motivation

This test is intended to cover that it is possible to close during asynchronous creation. But this can be a lot of cases, so it does not make sense. So I removed that section of the test

### Modifications

- Remove async close table view case.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: tests/TableViewTest.cc [hunk 1]
```diff
@@ -58,7 +58,7 @@ TEST(TableViewTest, testCreateTableView) {
     // Test async create and close the client during the process.
     Latch latch(1);
     client.createTableViewAsync(
-        topic, tableViewConfiguration, [&latch](Result result, const TableView& tableView) {
+        topic, {.schemaInfo = schemaInfo}, [&latch](Result result, const TableView& tableView) {
```
Comment (RobertIndie) [inline tests/TableViewTest.cc:61]: Why is it flaky when using the incompatible schema? It should always fail but it didn't,

Comment (shibd) [reply tests/TableViewTest.cc:61]: Because this is to close the tableView during asynchronous creation. 

I thought about it for a moment, and it is also problematic to modify it like this. It is possible to receive `result == ResultOk`

This test is intended to cover that it is possible to close during asynchronous creation. But this can be a lot of cases, so it does not make sense. So I removed that section of the test

**Review by RobertIndie — APPROVED** [review]
Yes. This part is flaky. Better to remove it.

We also need to update the PR description.
